export default {
	OPEN_TIME_SUCCESS: 'OPEN_TIME_SUCCESS',
	OPEN_TIME_ERROR: 'OPEN_TIME_ERROR',
	PLACES_DROPDOWN_SUCCESS: 'PLACES_DROPDOWN_SUCCESS',
	PLACES_DROPDOWN_ERROR: 'PLACES_DROPDOWN_ERROR',
	SEARCH_PLACES_SUCCESS: 'SEARCH_PLACES_SUCCESS',
	SEARCH_PLACES_ERROR: 'SEARCH_PLACES_ERROR',
	PLACES_TYPES_SUCCESS: 'PLACES_TYPES_SUCCESS',
	PLACES_TYPES_ERROR: 'PLACES_TYPES_ERROR',
	GET_PLACE_BY_ID_SUCCESS: 'GET_PLACE_BY_ID_SUCCESS',
	GET_PLACE_BY_ID_ERROR: 'GET_PLACE_BY_ID_ERROR',
	SEARCH_AVAILABLE_TABLES_SUCCESS: 'SEARCH_AVAILABLE_TABLES_SUCCESS',
	SEARCH_AVAILABLE_TABLES_ERROR: 'SEARCH_AVAILABLE_TABLES_ERROR',
	BOOK_TABLE_SUCCESS: 'BOOK_TABLE_SUCCESS',
	BOOK_TABLE_ERROR: 'BOOK_TABLE_ERROR',
	ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
	ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR',
	SAVE_SEARCH_FORM: 'SAVE_SEARCH_FORM'
}